use wallet;
/*insert en la tabla usuario*/
insert into `user`(`name`,last_name,email,`password`,validated) values('Charlotte','Oscar','consectetuer.adipiscing.elit@nisinibhlacinia.com','SXW42MFB4JA',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Gareth','Cullen','dui.nec@netus.org','XVX37QPW6ND',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Brenden','Rhoda','tellus.imperdiet@etpedeNunc.ca','TEY26AUJ0LI',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Eric','Paul','in.molestie@Curabiturmassa.com','EPW64ABC0RI',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Tanner','Latifah','auctor@pharetrautpharetra.com','DWK87DJJ5FN',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Lucy','Myles','amet.ultricies.sem@inceptoshymenaeos.org','RPQ86RWN5YB',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Jasmine','Kareem','vitae@nec.edu','WLF88HQX6KB',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Duncan','Cain','montes@elit.net','MZW48FKB6AZ',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Fitzgerald','Lysandra','quis@sociis.com','DDG32HMV3SH',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Benedict','Kim','tellus.sem@tristiquepellentesquetellus.net','VKJ71MUY3PW',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Melinda','William','felis.Donec.tempor@bibendumDonecfelis.co.uk','KLM70HZU0IH',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Camille','Robert','leo@Integer.co.uk','YNB63HTG3NK',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Calista','Aaron','varius@tellusimperdietnon.net','ZWV35GYU2QC',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Sean','Meghan','dictum.augue.malesuada@torquentperconubia.net','ADX56NDR2RQ',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Risa','Cole','tellus@Nam.net','BOJ27GIJ8QA',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Renee','Simone','Praesent@sapienNunc.ca','TOV63AAG0AN',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Vanna','Tanek','hymenaeos@Quisqueporttitoreros.edu','EXQ18BTM4GZ',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Patrick','Benjamin','gravida.mauris.ut@mattisCras.net','QDF32QCZ4BX',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Isabelle','Graiden','ut.lacus.Nulla@quisarcu.org','BFE34CLG4WW',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Blaine','Aubrey','sed.hendrerit@atsem.com','YAA84UBX6LW',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Mufutau','Tate','ornare.sagittis.felis@hendreritDonec.ca','QDK51ZRD0EW',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Graham','Cody','ipsum.dolor.sit@mattisornarelectus.com','TEQ91OEO2HW',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Kevyn','Hamilton','elementum.dui@amet.ca','ETH85TNM6WN',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Megan','August','Integer.vulputate.risus@Cum.net','WJR76UFD9XO',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Davis','Justin','mi.enim.condimentum@risusodio.net','JCS88FQV7VC',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Driscoll','Dominique','Vivamus@dapibusquam.com','KYG77HUA9KG',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Ifeoma','Tara','tincidunt.vehicula@Curabitur.org','DGO60GDU7PM',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Laith','Xavier','eu@neceleifendnon.ca','KRS67CHA2GY',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Gavin','Wanda','felis.orci.adipiscing@nullaante.net','FYH93PHU0GX',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Cyrus','Jasper','mi.pede.nonummy@interdumNuncsollicitudin.net','RFB79ZIM1SZ',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Madeson','Shelby','nec.orci@perinceptoshymenaeos.ca','NXX23PJH6FO',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Hyacinth','Tanisha','dictum@scelerisquescelerisque.edu','EBW55WJQ5MR',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Hasad','Price','consectetuer.adipiscing@lobortis.com','MLT30OKV5CW',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Felicia','Dorian','cursus.non@magnaPraesentinterdum.com','ZDG02YFL8FC',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Carlos','Conan','tristique@atsemmolestie.ca','XUL24XQA3ZF',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Ila','Serina','ut.pellentesque@pretium.edu','AYI41LKE5TI',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Victoria','Wade','interdum.Nunc@inconsequat.net','HLW27HKW3YH',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Maris','Ryan','Donec.porttitor.tellus@laoreetipsumCurabitur.net','FUD88PSJ4LV',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Guy','Leah','id.ante@neceuismodin.org','ZYH38ZJZ0RX',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Cain','Kato','dignissim.tempor@sapiengravidanon.net','LNZ77MSB1YW',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Indigo','Whitney','lorem@Quisqueac.co.uk','CRK67ULG7NG',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Chloe','Haviva','aliquet.metus@convallisdolorQuisque.com','SIC67TEG2DZ',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Francis','Abel','pede@antedictummi.net','MLV35SXP9OX',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Hyacinth','Hadassah','at.lacus.Quisque@Suspendisse.com','PHE78VGN4NA',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Drake','Jesse','sagittis.augue@ametmetus.org','LIV80NNU1IY',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Burke','Lyle','dignissim.lacus@felis.net','FSX48ZGS4UQ',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Phelan','Jana','ridiculus.mus@cursusinhendrerit.co.uk','BXE82ESH0QX',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Daryl','Calista','Etiam.laoreet.libero@ligula.com','VPD42CST3DU',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Sarah','Armando','vestibulum@ultricessitamet.org','WAR82ZRA7DG',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Kendall','Addison','Vivamus.molestie@pellentesque.co.uk','JCV00TKJ2BJ',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Jerome','Sasha','aliquet@tellusid.ca','GRL62DJD6PL',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Shaeleigh','Inga','pulvinar.arcu@arcu.ca','LIG31LGK4IE',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Leslie','Barry','risus@nequeMorbi.co.uk','YTE89MMM7QS',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Karyn','Calvin','consectetuer@eueuismodac.ca','QWI50FJE9HE',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Sierra','Hadley','velit.in.aliquet@DonecegestasDuis.net','WDA49RUI4QH',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Gloria','Shoshana','at@Etiamlaoreetlibero.edu','GAO81SSB8VJ',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Gisela','Audrey','pulvinar.arcu@malesuada.net','FZG59IMP0CK',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Kyra','Sebastian','et.netus.et@elitCurabitur.ca','TDZ69WFD9GA',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Chandler','Akeem','mi@dictummiac.net','HKB54FDJ6BF',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Germane','Dominic','eu@velvenenatisvel.co.uk','ODX23JZO3YA',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Aidan','Chase','dignissim.pharetra.Nam@veliteu.org','WNY07HMO1HR',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Cassandra','Justin','In.lorem.Donec@maurisid.ca','YKY91DNT3FX',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Gage','Jamal','aliquet.Proin.velit@Nuncquis.org','DYI87XWU6IP',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Zelenia','Jesse','Sed@volutpat.com','RZS30UUY7FW',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Bradley','Wade','elit.a@mieleifend.com','GXH35QBM6PV',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Farrah','Alisa','Integer.in@infaucibusorci.co.uk','DMB86FNC6CO',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Carson','Dexter','In.mi@Namnullamagna.co.uk','NMR38BVF5ZY',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Callie','Anastasia','Integer@molestiedapibusligula.net','VDZ35TQE8GH',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Veronica','Castor','mi@egettincidunt.com','WLE67TQK7NZ',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Sydney','Jin','Curabitur.ut@orciconsectetuereuismod.ca','PPP56IJO3VI',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Chadwick','Hu','placerat.Cras.dictum@nequetellus.org','LFD86GDO2RW',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Jakeem','Ross','sem.egestas@blanditenimconsequat.com','IBN09DBV0UR',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Joseph','Gavin','luctus.ut@semegetmassa.com','REG94VRH6GK',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Lesley','Kirby','Vivamus@pulvinararcu.org','XBH75RXC1HZ',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Breanna','Emerald','faucibus.orci@eratnequenon.edu','YYZ75LWG4NC',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Wesley','Elaine','amet.dapibus.id@apurus.co.uk','ZPW80LXH6TP',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Maxwell','Cherokee','pharetra@faucibus.ca','FGE56QFS5XP',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Jonas','Reese','odio.tristique.pharetra@tempor.org','QWX61XYX1DD',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Athena','Ann','In@dictumsapienAenean.ca','UHW94SOJ0JA',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Ciara','Ariana','ornare@sitametdapibus.co.uk','ORI17YDY1CC',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Sage','Serena','Curabitur@quamelementumat.co.uk','JVH19OBT5QY',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Robin','Brenden','sagittis.semper@Fusce.co.uk','ONW41XKD1WO',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Kaden','Darryl','Cras.sed@euerosNam.com','VRI42JKT8VW',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Denton','Norman','tellus.id@duiFuscealiquam.org','SXJ67JNK5PC',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Larissa','Arsenio','volutpat.Nulla@mifelis.co.uk','CTQ65SIC7MT',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Pandora','Savannah','eget@est.ca','ZMB75EDX9XP',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Lars','Cameron','lectus.ante@ataugue.org','BJF04NTG4FJ',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Ulysses','Shelby','tincidunt@Maurisvelturpis.com','KUL20YID9NY',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Mannix','Cameron','felis@loremacrisus.edu','GWM56MAL8QV',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Zeus','Mira','Etiam.ligula.tortor@anteMaecenasmi.edu','UMP58WHH9KX',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Olga','Guy','nisi@ametrisus.ca','VOC30UZP7XL',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Susan','Kevyn','et@Suspendisseacmetus.ca','CRW05LUF0CS',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Hermione','Tatum','pretium.et.rutrum@idrisus.com','KSU07CNV9LJ',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Paul','Walter','egestas@elitpharetraut.ca','ZCS31QKG4SW',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Sierra','Jana','massa.Quisque.porttitor@utaliquamiaculis.com','WOX82NOU0EU',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Walter','Maia','erat.Vivamus.nisi@Proinsedturpis.edu','NOX20HJO1CO',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Rashad','Kylie','lacus.Ut.nec@Nullafacilisis.org','IGX46ZMJ2PL',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Hunter','Matthew','In.mi.pede@natoquepenatibus.co.uk','FVX57VES6VD',1); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Kibo','Aquila','netus.et.malesuada@etipsum.ca','GFU60SND1XW',0); 
insert into `user`(`name`,last_name,email,`password`,validated) values('Maggie','Martha','consequat.lectus.sit@hendreritDonec.ca','IBC45OGG5DC',1); 

/*insert en la tabla validacion email*/
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(54,53,27,71,49);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(37,1,46,37,12);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(13,1,6,95,6);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(18,73,41,73,9);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(21,43,7,33,86);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(84,0,89,31,64);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(87,54,9,84,37);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(69,57,67,64,54);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(42,39,35,61,20);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(88,80,24,69,75);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(60,13,96,47,95);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(23,98,53,19,19);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(6,64,71,90,88);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(21,90,35,25,24);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(17,61,80,27,94);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(65,37,37,16,24);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(5,30,50,31,88);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(11,39,83,17,7);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(19,73,71,22,57);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(96,55,80,67,41);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(42,9,93,91,88);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(71,39,86,64,17);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(79,40,45,90,2);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(12,63,7,80,28);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(83,77,49,58,57);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(27,48,49,16,61);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(22,96,12,50,68);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(59,98,19,85,92);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(47,16,38,43,51);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(87,50,64,66,78);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(40,84,72,10,69);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(29,16,24,67,93);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(27,16,3,26,7);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(49,19,41,43,18);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(92,90,35,58,5);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(91,98,97,80,15);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(53,56,17,43,17);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(21,45,70,3,35);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(30,53,47,72,3);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(73,98,60,39,40);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(46,92,69,78,83);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(82,10,59,75,22);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(89,86,16,10,14);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(52,92,7,32,78);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(93,99,38,59,30);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(52,74,63,70,44);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(2,83,68,68,10);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(71,61,51,53,5);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(97,69,95,16,37);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(67,39,60,36,98);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(2,41,85,78,57);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(32,72,87,4,49);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(80,61,24,61,61);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(56,54,92,47,36);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(60,96,94,92,79);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(40,68,80,30,84);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(25,23,36,40,17);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(53,24,55,88,36);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(83,2,9,32,2);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(25,2,80,41,23);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(61,86,13,37,32);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(5,10,15,77,71);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(88,4,8,23,23);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(66,78,58,86,86);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(77,70,21,53,51);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(96,46,52,99,96);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(63,63,99,52,75);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(87,11,68,11,29);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(75,34,24,85,1);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(93,99,49,13,96);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(97,95,40,75,16);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(72,73,76,51,36);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(4,32,70,74,13);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(70,6,57,91,5);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(31,84,8,95,9);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(5,6,35,83,92);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(73,49,33,60,48);
insert into `mail_validation`(code_1,code_2,code_3,`code_4`,id_user) values(75,98,86,97,65);

/*inserciones en la tabla tipo de transaccion*/ 
insert into `transaction_type`(nameTransaction,descriptionTransaction) values('Salida','Se realizo una salida de capital');
insert into `transaction_type`(nameTransaction,descriptionTransaction) values('Entrada','Se obtuvo una entrada de capital');

/*insersions de tipo detalle de transacciones*/
insert into transaction_detail(id_user,idTransactionType,mount) values(95,2,233);
insert into transaction_detail(id_user,idTransactionType,mount) values(48,2,7139);
insert into transaction_detail(id_user,idTransactionType,mount) values(89,1,5029);
insert into transaction_detail(id_user,idTransactionType,mount) values(82,1,1983);
insert into transaction_detail(id_user,idTransactionType,mount) values(72,1,1957);
insert into transaction_detail(id_user,idTransactionType,mount) values(80,2,4876);
insert into transaction_detail(id_user,idTransactionType,mount) values(35,2,49);
insert into transaction_detail(id_user,idTransactionType,mount) values(5,1,4261);
insert into transaction_detail(id_user,idTransactionType,mount) values(80,2,7679);
insert into transaction_detail(id_user,idTransactionType,mount) values(36,2,1470);
insert into transaction_detail(id_user,idTransactionType,mount) values(84,2,542);
insert into transaction_detail(id_user,idTransactionType,mount) values(42,1,5987);
insert into transaction_detail(id_user,idTransactionType,mount) values(52,1,8900);
insert into transaction_detail(id_user,idTransactionType,mount) values(86,2,3449);
insert into transaction_detail(id_user,idTransactionType,mount) values(24,2,7737);
insert into transaction_detail(id_user,idTransactionType,mount) values(8,2,6596);
insert into transaction_detail(id_user,idTransactionType,mount) values(49,1,6345);
insert into transaction_detail(id_user,idTransactionType,mount) values(24,1,4053);
insert into transaction_detail(id_user,idTransactionType,mount) values(58,1,7238);
insert into transaction_detail(id_user,idTransactionType,mount) values(19,2,8746);
insert into transaction_detail(id_user,idTransactionType,mount) values(69,1,538);
insert into transaction_detail(id_user,idTransactionType,mount) values(34,2,7899);
insert into transaction_detail(id_user,idTransactionType,mount) values(62,1,4128);
insert into transaction_detail(id_user,idTransactionType,mount) values(17,2,8969);
insert into transaction_detail(id_user,idTransactionType,mount) values(77,2,8777);
insert into transaction_detail(id_user,idTransactionType,mount) values(22,1,5057);
insert into transaction_detail(id_user,idTransactionType,mount) values(69,1,925);
insert into transaction_detail(id_user,idTransactionType,mount) values(20,1,1132);
insert into transaction_detail(id_user,idTransactionType,mount) values(57,2,9242);
insert into transaction_detail(id_user,idTransactionType,mount) values(1,2,8242);
insert into transaction_detail(id_user,idTransactionType,mount) values(13,2,693);
insert into transaction_detail(id_user,idTransactionType,mount) values(66,1,8031);
insert into transaction_detail(id_user,idTransactionType,mount) values(82,2,8355);
insert into transaction_detail(id_user,idTransactionType,mount) values(81,1,9289);
insert into transaction_detail(id_user,idTransactionType,mount) values(72,1,8714);
insert into transaction_detail(id_user,idTransactionType,mount) values(17,1,9406);
insert into transaction_detail(id_user,idTransactionType,mount) values(26,2,7224);
insert into transaction_detail(id_user,idTransactionType,mount) values(44,1,3560);
insert into transaction_detail(id_user,idTransactionType,mount) values(65,2,6343);
insert into transaction_detail(id_user,idTransactionType,mount) values(87,1,6522);
insert into transaction_detail(id_user,idTransactionType,mount) values(53,1,6054);
insert into transaction_detail(id_user,idTransactionType,mount) values(88,2,9644);
insert into transaction_detail(id_user,idTransactionType,mount) values(31,1,8087);
insert into transaction_detail(id_user,idTransactionType,mount) values(60,2,5854);
insert into transaction_detail(id_user,idTransactionType,mount) values(98,1,1598);
insert into transaction_detail(id_user,idTransactionType,mount) values(16,2,660);
insert into transaction_detail(id_user,idTransactionType,mount) values(84,2,9927);
insert into transaction_detail(id_user,idTransactionType,mount) values(52,1,8223);
insert into transaction_detail(id_user,idTransactionType,mount) values(53,2,7789);
insert into transaction_detail(id_user,idTransactionType,mount) values(13,2,5006);
insert into transaction_detail(id_user,idTransactionType,mount) values(35,2,7778);
insert into transaction_detail(id_user,idTransactionType,mount) values(7,1,7543);
insert into transaction_detail(id_user,idTransactionType,mount) values(8,1,6832);
insert into transaction_detail(id_user,idTransactionType,mount) values(74,2,8666);
insert into transaction_detail(id_user,idTransactionType,mount) values(42,2,3426);
insert into transaction_detail(id_user,idTransactionType,mount) values(32,1,9038);
insert into transaction_detail(id_user,idTransactionType,mount) values(9,2,8364);
insert into transaction_detail(id_user,idTransactionType,mount) values(44,2,2237);
insert into transaction_detail(id_user,idTransactionType,mount) values(86,1,4630);
insert into transaction_detail(id_user,idTransactionType,mount) values(52,1,3119);
insert into transaction_detail(id_user,idTransactionType,mount) values(84,1,1747);
insert into transaction_detail(id_user,idTransactionType,mount) values(28,2,4911);
insert into transaction_detail(id_user,idTransactionType,mount) values(60,2,4514);
insert into transaction_detail(id_user,idTransactionType,mount) values(26,2,569);
insert into transaction_detail(id_user,idTransactionType,mount) values(72,2,3315);
insert into transaction_detail(id_user,idTransactionType,mount) values(83,2,821);
insert into transaction_detail(id_user,idTransactionType,mount) values(91,2,598);
insert into transaction_detail(id_user,idTransactionType,mount) values(77,2,2323);
insert into transaction_detail(id_user,idTransactionType,mount) values(99,1,2401);
insert into transaction_detail(id_user,idTransactionType,mount) values(13,2,9508);
insert into transaction_detail(id_user,idTransactionType,mount) values(83,1,4478);
insert into transaction_detail(id_user,idTransactionType,mount) values(83,1,9407);
insert into transaction_detail(id_user,idTransactionType,mount) values(93,2,4892);
insert into transaction_detail(id_user,idTransactionType,mount) values(59,2,8103);
insert into transaction_detail(id_user,idTransactionType,mount) values(61,1,1272);
insert into transaction_detail(id_user,idTransactionType,mount) values(65,1,3162);
insert into transaction_detail(id_user,idTransactionType,mount) values(52,2,2672);
insert into transaction_detail(id_user,idTransactionType,mount) values(92,2,6820);
insert into transaction_detail(id_user,idTransactionType,mount) values(73,2,207);
insert into transaction_detail(id_user,idTransactionType,mount) values(55,1,7119);
insert into transaction_detail(id_user,idTransactionType,mount) values(36,2,721);
insert into transaction_detail(id_user,idTransactionType,mount) values(13,2,830);
insert into transaction_detail(id_user,idTransactionType,mount) values(57,1,3574);
insert into transaction_detail(id_user,idTransactionType,mount) values(7,2,2245);
insert into transaction_detail(id_user,idTransactionType,mount) values(81,2,3575);
insert into transaction_detail(id_user,idTransactionType,mount) values(21,1,3407);
insert into transaction_detail(id_user,idTransactionType,mount) values(7,2,1670);
insert into transaction_detail(id_user,idTransactionType,mount) values(6,1,576);
insert into transaction_detail(id_user,idTransactionType,mount) values(88,1,3276);
insert into transaction_detail(id_user,idTransactionType,mount) values(64,1,3914);
insert into transaction_detail(id_user,idTransactionType,mount) values(88,1,7742);
insert into transaction_detail(id_user,idTransactionType,mount) values(48,1,7511);
insert into transaction_detail(id_user,idTransactionType,mount) values(35,2,9641);
insert into transaction_detail(id_user,idTransactionType,mount) values(52,2,9954);
insert into transaction_detail(id_user,idTransactionType,mount) values(75,2,4052);
insert into transaction_detail(id_user,idTransactionType,mount) values(80,2,6246);
insert into transaction_detail(id_user,idTransactionType,mount) values(5,1,5638);
insert into transaction_detail(id_user,idTransactionType,mount) values(32,1,5123);
insert into transaction_detail(id_user,idTransactionType,mount) values(75,1,5170);
insert into transaction_detail(id_user,idTransactionType,mount) values(44,1,7161); 

/*inserciones de metas*/
insert into goal(id_user,mount,detail) values(43,7273,"Realizar un ahorro de 7273 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(11,8486,"Realizar un ahorro de 8486 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(4,8925,"Realizar un ahorro de 8925 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(46,7437,"Realizar un ahorro de 7437 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(42,6158,"Realizar un ahorro de 6158 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(11,1882,"Realizar un ahorro de 1882 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(13,8198,"Realizar un ahorro de 8198 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(76,4404,"Realizar un ahorro de 4404 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(10,6558 ,"Realizar un ahorro de 6558 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(73,2496 ,"Realizar un ahorro de 2496 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(50,8137,"Realizar un ahorro de 8137 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(29,5255 ,"Realizar un ahorro de 5255 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(76,9720,"Realizar un ahorro de 9720 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(6,2607,"Realizar un ahorro de 2607 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(73,4879,"Realizar un ahorro de 4879 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(83,6488,"Realizar un ahorro de 6488 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(47,1949,"Realizar un ahorro de 1949 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(96,454,"Realizar un ahorro de 454 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(29,8303,"Realizar un ahorro de 8303 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(1,2912,"Realizar un ahorro de 2912 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(29,6916,"Realizar un ahorro de 6916 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(85,2030,"Realizar un ahorro de 2030 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(67,4756,"Realizar un ahorro de 4756 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(69,1501,"Realizar un ahorro de 1501 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(57,9079,"Realizar un ahorro de 9079 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(30,3353,"Realizar un ahorro de 3353 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(41,1253,"Realizar un ahorro de 1253 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(52,9169,"Realizar un ahorro de 9169 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(87,9839,"Realizar un ahorro de 9839 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(33,9852,"Realizar un ahorro de 9852 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(38,787,"Realizar un ahorro de 787 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(18,3809,"Realizar un ahorro de 3809 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(52,8172,"Realizar un ahorro de 8172 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(81,5332,"Realizar un ahorro de 5332 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(61,5840,"Realizar un ahorro de 5840 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(70,4079,"Realizar un ahorro de 4079 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(44,8739,"Realizar un ahorro de 8739 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(91,9465,"Realizar un ahorro de 9465 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(81,7038,"Realizar un ahorro de 7038 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(2,802,"Realizar un ahorro de 802 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(30,2340,"Realizar un ahorro de 2340 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(72,3523,"Realizar un ahorro de 3523 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(3,1577,"Realizar un ahorro de 1577 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(26,4361,"Realizar un ahorro de 4361 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(59,7803,"Realizar un ahorro de 7803 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(31,5299,"Realizar un ahorro de 5299 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(85,8751,"Realizar un ahorro de 8751 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(35,1709,"Realizar un ahorro de 1709 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(86,9454,"Realizar un ahorro de 9454 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(52,7052,"Realizar un ahorro de 7052 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(32,7516,"Realizar un ahorro de 7516 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(91,9318,"Realizar un ahorro de 9318 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(74,9124,"Realizar un ahorro de 9124 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(58,7011,"Realizar un ahorro de 7011 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(40,4481,"Realizar un ahorro de 4481 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(3,382,"Realizar un ahorro de 382 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(24,9638,"Realizar un ahorro de 9638 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(44,5565,"Realizar un ahorro de 5565 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(71,3721,"Realizar un ahorro de 3721 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(60,2721,"Realizar un ahorro de 2721 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(75,997,"Realizar un ahorro de 997 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(46,7404,"Realizar un ahorro de 7404 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(46,6334,"Realizar un ahorro de 6334 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(16,5267,"Realizar un ahorro de 5267 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(39,2230,"Realizar un ahorro de 2230 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(31,5230,"Realizar un ahorro de 5230 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(98,8538,"Realizar un ahorro de 8538 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(49,2244,"Realizar un ahorro de 2244 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(19,7673,"Realizar un ahorro de 7673 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(12,7878,"Realizar un ahorro de 7878 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(29,2390,"Realizar un ahorro de 2390 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(21,3313,"Realizar un ahorro de 3313 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(90,7881,"Realizar un ahorro de 7881 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(15,7412,"Realizar un ahorro de 7412 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(90,8779,"Realizar un ahorro de 8779 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(10,4832,"Realizar un ahorro de 4832 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(63,1503,"Realizar un ahorro de 1503 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(20,2770,"Realizar un ahorro de 2770 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(64,2738,"Realizar un ahorro de 2738 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(60,5001,"Realizar un ahorro de 5001 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(38,3394,"Realizar un ahorro de 3394 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(55,1307,"Realizar un ahorro de 1307 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(47,3915,"Realizar un ahorro de 3915 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(82,1096,"Realizar un ahorro de 1096 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(25,1699,"Realizar un ahorro de 1699 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(29,4267,"Realizar un ahorro de 4267 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(89,4840,"Realizar un ahorro de 4840 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(42,2822,"Realizar un ahorro de 2822 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(30,9128,"Realizar un ahorro de 9128 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(34,3618,"Realizar un ahorro de 3618 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(50,6280,"Realizar un ahorro de 6280 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(42,4074,"Realizar un ahorro de 4074 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(82,9693,"Realizar un ahorro de 9693 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(77,7545,"Realizar un ahorro de 7545 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(55,5958,"Realizar un ahorro de 5958 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(59,1697,"Realizar un ahorro de 1697 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(76,5070,"Realizar un ahorro de 5070 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(87,2122,"Realizar un ahorro de 2122 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(52,5165,"Realizar un ahorro de 5165 las salidas del presente mes");
insert into goal(id_user,mount,detail) values(94,3619,"Realizar un ahorro de 3619 las salidas del presente mes"); 

/*insert cuenta bancos*/

insert into bank_account(name_bank_account,id_user,mount) values("Banrural",43,7273);
insert into bank_account(name_bank_account,id_user,mount) values("Banco el pais",11,8486);
insert into bank_account(name_bank_account,id_user,mount) values("Banco el pais",4,8925);
insert into bank_account(name_bank_account,id_user,mount) values("Copeerativa Elga",46,7437);
insert into bank_account(name_bank_account,id_user,mount) values("Copeerativa Elga",42,6158);
insert into bank_account(name_bank_account,id_user,mount) values("Davivienda",11,1882);
insert into bank_account(name_bank_account,id_user,mount) values("Banrural",13,8198);
insert into bank_account(name_bank_account,id_user,mount) values("Banpais",76,4404);
insert into bank_account(name_bank_account,id_user,mount) values("Banpais",10,6558);
insert into bank_account(name_bank_account,id_user,mount) values("Banrural",73,2496);
insert into bank_account(name_bank_account,id_user,mount) values("Copeerativa Elga",50,8137); 
insert into bank_account(name_bank_account,id_user,mount) values("Banpais",29,5255); 
insert into bank_account(name_bank_account,id_user,mount) values("Davivienda",76,9720); 
insert into bank_account(name_bank_account,id_user,mount) values("Banpais",6,2607); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco el pais",73,4879); 
insert into bank_account(name_bank_account,id_user,mount) values("Banpais",83,6488); 
insert into bank_account(name_bank_account,id_user,mount) values("Copeerativa Elga",47,1949); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco el pais",96,454); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco el pais",29,8303); 
insert into bank_account(name_bank_account,id_user,mount) values("Banpais",1,2912); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco Occidente",29,6916); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco Atlantidad",85,2030); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco Occidente",67,4756); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco Occidente",69,1501); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco Occidente",57,9079); 
insert into bank_account(name_bank_account,id_user,mount) values("Davivienda",30,3353); 
insert into bank_account(name_bank_account,id_user,mount) values("Davivienda",41,1253); 
insert into bank_account(name_bank_account,id_user,mount) values("Banpais",52,9169); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco el pais",87,9839); 
insert into bank_account(name_bank_account,id_user,mount) values("Banrural",33,9852); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco Atlantidad",38,787); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco Atlantidad",18,3809); 
insert into bank_account(name_bank_account,id_user,mount) values("Copeerativa Elga",52,8172); 
insert into bank_account(name_bank_account,id_user,mount) values("Banrural",81,5332); 
insert into bank_account(name_bank_account,id_user,mount) values("Banpais",61,5840); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco el pais",70,4079); 
insert into bank_account(name_bank_account,id_user,mount) values("Davivienda",44,8739); 
insert into bank_account(name_bank_account,id_user,mount) values("Copeerativa Elga",91,9465); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco Atlantidad",81,7038); 
insert into bank_account(name_bank_account,id_user,mount) values("Banpais",2,802); 
insert into bank_account(name_bank_account,id_user,mount) values("Copeerativa Elga",30,2340); 
insert into bank_account(name_bank_account,id_user,mount) values("Copeerativa Elga",72,3523); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco Atlantidad",3,1577); 
insert into bank_account(name_bank_account,id_user,mount) values("Davivienda",26,4361); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco el pais",59,7803); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco Occidente",31,5299); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco Atlantidad",85,8751); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco Atlantidad",35,1709); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco Occidente",86,9454); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco el pais",52,7052); 
insert into bank_account(name_bank_account,id_user,mount) values("Davivienda",32,7516); 
insert into bank_account(name_bank_account,id_user,mount) values("Copeerativa Elga",91,9318); 
insert into bank_account(name_bank_account,id_user,mount) values("Banrural",74,9124); 
insert into bank_account(name_bank_account,id_user,mount) values("Davivienda",58,7011); 
insert into bank_account(name_bank_account,id_user,mount) values("Davivienda",40,4481); 
insert into bank_account(name_bank_account,id_user,mount) values("Copeerativa Elga",3,382); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco Atlantidad",24,9638); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco Occidente",44,5565); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco Atlantidad",71,3721); 
insert into bank_account(name_bank_account,id_user,mount) values("Banpais",60,2721); 
insert into bank_account(name_bank_account,id_user,mount) values("Banpais",75,997); 
insert into bank_account(name_bank_account,id_user,mount) values("Banpais",46,7404); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco el pais",46,6334); 
insert into bank_account(name_bank_account,id_user,mount) values("Davivienda",16,5267); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco Atlantidad",39,2230); 
insert into bank_account(name_bank_account,id_user,mount) values("Banpais",31,5230); 
insert into bank_account(name_bank_account,id_user,mount) values("Copeerativa Elga",98,8538); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco el pais",49,2244); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco Atlantidad",19,7673); 
insert into bank_account(name_bank_account,id_user,mount) values("Davivienda",12,7878); 
insert into bank_account(name_bank_account,id_user,mount) values("Davivienda",29,2390); 
insert into bank_account(name_bank_account,id_user,mount) values("Banrural",21,3313); 
insert into bank_account(name_bank_account,id_user,mount) values("Banpais",90,7881); 
insert into bank_account(name_bank_account,id_user,mount) values("Banpais",15,7412); 
insert into bank_account(name_bank_account,id_user,mount) values("Davivienda",90,8779); 
insert into bank_account(name_bank_account,id_user,mount) values("Davivienda",10,4832); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco Occidente",63,1503); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco Occidente",20,2770); 
insert into bank_account(name_bank_account,id_user,mount) values("Banpais",64,2738); 
insert into bank_account(name_bank_account,id_user,mount) values("Banpais",60,5001); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco Occidente",38,3394); 
insert into bank_account(name_bank_account,id_user,mount) values("Copeerativa Elga",55,1307); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco Atlantidad",47,3915); 
insert into bank_account(name_bank_account,id_user,mount) values("Copeerativa Elga",82,1096); 
insert into bank_account(name_bank_account,id_user,mount) values("Davivienda",25,1699); 
insert into bank_account(name_bank_account,id_user,mount) values("Banrural",29,4267); 
insert into bank_account(name_bank_account,id_user,mount) values("Banrural",89,4840); 
insert into bank_account(name_bank_account,id_user,mount) values("Banrural",42,2822); 
insert into bank_account(name_bank_account,id_user,mount) values("Banrural",30,9128); 
insert into bank_account(name_bank_account,id_user,mount) values("Copeerativa Elga",34,3618); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco el pais",50,6280); 
insert into bank_account(name_bank_account,id_user,mount) values("Banpais",42,4074); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco Occidente",82,9693); 
insert into bank_account(name_bank_account,id_user,mount) values("Banpais",77,7545); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco Atlantidad",55,5958); 
insert into bank_account(name_bank_account,id_user,mount) values("Banco el pais",59,1697); 
insert into bank_account(name_bank_account,id_user,mount) values("Banrural",76,5070); 
insert into bank_account(name_bank_account,id_user,mount) values("Copeerativa Elga",87,2122); 
insert into bank_account(name_bank_account,id_user,mount) values("Davivienda",52,5165); 
insert into bank_account(name_bank_account,id_user,mount) values("Banpais",94,3619); 


insert into categorie(`name`) values
    ('a'),
    ('b'); 
